
services:
  bancoapi_postgres:
    image: postgres
    container_name: bancoapi_postgres_container
    environment:
      POSTGRES_DB: bancoapi_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - bancoapi-rede
    ports:
      - "5432:5432"
    volumes:
      - bancoapi_pgdata:/var/lib/postgresql/data

  bancoapi_rabbitmq:
    image: heidiks/rabbitmq-delayed-message-exchange:latest
    container_name: bancoapi_rabbitmq_container
    ports:
      - "5672:5672"
      - "15672:15672"
    command: >
      sh -c "rabbitmq-plugins enable --offline rabbitmq_delayed_message_exchange &&
             rabbitmq-server"
    networks:
      - bancoapi-rede

 

volumes:
  bancoapi_pgdata:

networks:
  bancoapi-rede:
    driver: bridge
